#' askgpt
#'
#' @param prompt The prompt sent to chatGPT
#'
#' @examples
#' \dontrun{
#' cat(ask_chatgpt("How many ducks does it take to screw in a lightulb?"))
#' }
#'
#' @return A character value with the response to be generated by ChatGPT.
#'
#' @export
#'
askgpt <- function(prompt) {
  parse_response(gpt_get_completions(prompt))
}
